const constants = {
    LOG_IN: "LOG_IN",
    LOG_OUT: "LOG_OUT",
    UPDATE_BALANCE: "UPDATE_BALANCE",
    CREATE_TRANSACTION: "CREATE_TRANSACTION",
    UPDATE_EXCHANGE_RATE: "UPDATE_EXCHANGE_RATE"
}

export default constants